blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/software-mansion-labs/react-native-nano-icons/discussions/categories/q-a
    about: Please ask and answer questions here.
