/** @jest-environment node */

// Expected values in the fixture were generated by running the original
// picosvg 0.22.3 python source (svg_transform / arc_to_cubic / svg_path_iter /
// svg_types) on the same inputs. The TS port must reproduce them exactly.

import expected from './fixtures/flatten-primitives-expected.json';
import { ntos, pt, pythonRound } from '../src/core/svg/flatten/geometry';
import { Affine2D, parseSvgTransform } from '../src/core/svg/flatten/transform';
import { arcToCubic } from '../src/core/svg/flatten/arcs';
import {
  absoluteMoveto,
  absolutePath,
  arcsToCubics,
  expandShorthand,
  explicitLines,
  parseSvgPath,
  pathSegment,
  roundFloatsD,
  subpaths,
} from '../src/core/svg/flatten/path';

// V8's Math.sin/cos/tan may differ from CPython's libm by 1 ulp, so anything
// downstream of trig gets a tolerance instead of exact equality.
function expectNumbersClose(
  got: readonly number[],
  want: readonly number[],
  relTol = 1e-12
): void {
  expect(got.length).toBe(want.length);
  for (let i = 0; i < got.length; i++) {
    const g = got[i]!;
    const w = want[i]!;
    const tol = Math.max(relTol, relTol * Math.abs(w));
    if (Math.abs(g - w) > tol) {
      expect(got).toEqual(want); // fails with a readable diff
    }
  }
}

describe('parseSvgTransform', () => {
  for (const [raw, values] of Object.entries(expected.transforms)) {
    test(`"${raw}"`, () => {
      expectNumbersClose(parseSvgTransform(raw).values(), values);
    });
  }

  test('compose_ltr', () => {
    const composed = Affine2D.composeLtr([
      parseSvgTransform('rotate(30)'),
      parseSvgTransform('translate(10 20)'),
      parseSvgTransform('scale(2)'),
    ]);
    expect(composed.values()).toEqual(expected.compose_ltr);
  });

  test('inverse', () => {
    const inv = parseSvgTransform('translate(1,2) rotate(30) scale(2,3)')
      .inverse()
      .values();
    expect(inv).toEqual(expected.inverse);
  });

  for (const [par, values] of Object.entries(expected.rect_to_rect)) {
    test(`rect_to_rect preserveAspectRatio="${par}"`, () => {
      const affine = Affine2D.rectToRect(
        { x: 0, y: 0, w: 24, h: 24 },
        { x: 10, y: 10, w: 100, h: 50 },
        par
      );
      expect(affine.values()).toEqual(values);
    });
  }

  test('toString', () => {
    expect(parseSvgTransform('translate(10 20)').toString()).toBe(
      expected.tostring['translate(10 20)']
    );
    expect(parseSvgTransform('rotate(45)').toString()).toBe(
      expected.tostring['rotate(45)']
    );
    expect(Affine2D.identity().toString()).toBe(expected.tostring.identity);
  });
});

describe('arcToCubic', () => {
  for (const { args, cubics } of expected.arcs) {
    const [start, rx, ry, rot, large, sweep, end] = args as [
      [number, number],
      number,
      number,
      number,
      number,
      number,
      [number, number],
    ];
    test(`arc ${JSON.stringify(args)}`, () => {
      const got = [
        ...arcToCubic(
          pt(start[0], start[1]),
          rx,
          ry,
          rot,
          large,
          sweep,
          pt(end[0], end[1])
        ),
      ].map(([p1, p2, endp]) => [
        p1 === null ? null : [p1.x, p1.y],
        p2 === null ? null : [p2.x, p2.y],
        [endp.x, endp.y],
      ]);
      expect(got.length).toBe(cubics.length);
      expectNumbersClose(
        got.flat(2).filter((v): v is number => v !== null),
        cubics.flat(2).filter((v): v is number => v !== null)
      );
    });
  }
});

describe('parseSvgPath', () => {
  for (const [d, { grouped, exploded }] of Object.entries(expected.parse)) {
    test(`"${d}"`, () => {
      expect(parseSvgPath(d)).toEqual(grouped);
      expect(parseSvgPath(d, true)).toEqual(exploded);
    });
  }
});

describe('d-string rewrites', () => {
  const ops: Record<string, (d: string) => string> = {
    explicit_lines: explicitLines,
    expand_shorthand: expandShorthand,
    absolute: absolutePath,
    arcs_to_cubics: arcsToCubics,
    absolute_moveto: absoluteMoveto,
    round_floats_3: (d) => roundFloatsD(d, 3),
    round_floats_2: (d) => roundFloatsD(d, 2),
  };

  for (const [opName, samples] of Object.entries(expected.dops)) {
    describe(opName, () => {
      for (const [input, output] of Object.entries(samples)) {
        test(`"${input}"`, () => {
          const got = ops[opName]!(input);
          if (opName === 'arcs_to_cubics') {
            // trig-derived floats: compare parsed numbers with tolerance
            const gotCmds = parseSvgPath(got, true);
            const wantCmds = parseSvgPath(output, true);
            expect(gotCmds.map(([c]) => c)).toEqual(wantCmds.map(([c]) => c));
            expectNumbersClose(
              gotCmds.flatMap(([, a]) => a),
              wantCmds.flatMap(([, a]) => a)
            );
          } else {
            expect(got).toBe(output);
          }
        });
      }
    });
  }

  for (const [input, output] of Object.entries(expected.subpaths)) {
    test(`subpaths "${input}"`, () => {
      expect(subpaths(input)).toEqual(output);
    });
  }
});

describe('formatting', () => {
  test('pathSegment', () => {
    expect(pathSegment('M', 1.0, 2.0)).toBe(expected.path_segment.M);
    expect(pathSegment('A', 2.5, 2.5, 0.0, 1, 1, 10.0, 0.0)).toBe(
      expected.path_segment.A
    );
    expect(pathSegment('C', 1, 2, 3, 4, 5, 6)).toBe(expected.path_segment.C);
    expect(pathSegment('H', 5.0)).toBe(expected.path_segment.H);
    expect(pathSegment('Z')).toBe(expected.path_segment.Z);
    expect(pathSegment('L', 1, 2, 3, 4)).toBe(expected.path_segment['L-multi']);
  });

  test('ntos', () => {
    for (const [input, output] of Object.entries(expected.ntos)) {
      expect(ntos(parseFloat(input))).toBe(output);
    }
  });

  test('pythonRound matches CPython round() semantics', () => {
    // pairs verified against python3: round(x, n)
    expect(pythonRound(0.155, 2)).toBe(0.15); // exact double is below the tie
    expect(pythonRound(0.145, 2)).toBe(0.14);
    expect(pythonRound(0.125, 2)).toBe(0.12); // true tie -> even
    expect(pythonRound(0.135, 2)).toBe(0.14); // true tie -> even
    expect(pythonRound(2.675, 2)).toBe(2.67);
    expect(pythonRound(0.9995, 3)).toBe(1);
    expect(pythonRound(1.0005, 3)).toBe(1);
    expect(pythonRound(2.5005, 3)).toBe(2.501);
    expect(pythonRound(-0.155, 2)).toBe(-0.15);
    expect(pythonRound(-0.125, 2)).toBe(-0.12);
    expect(pythonRound(7, 3)).toBe(7);
  });
});
