import fsp from 'node:fs/promises';
import path from 'node:path';

import { PathKitManager } from './managers.js';
import { ensureDir, ensureEmptyDir } from './config.js';
import { prepareSvgLayers } from './prepare.js';
import { shouldSkipPath } from '../svg/svg_dom.js';
import { resolveSymbolLayers, contentBounds } from '../svg/svg_pathops.js';
import { buildSymbolTemplate } from '../symbols/template.js';
import { buildColoredSymbolSvg } from '../symbols/coloredSymbol.js';
import {
  symbolsetContentsJson,
  imagesetContentsJson,
} from '../symbols/contents.js';
import type { NanoLogger } from '../types.js';

export type SymbolsPipelineConfig = {
  /** Set name (used for output filenames and the manifest export name). */
  name: string;
  /** Symbol name prefix, e.g. "nano" → "nano.home". */
  prefix: string;
  /** Emit colored `.imageset` (original colors) instead of monochrome `.symbolset`. */
  multicolor?: boolean;
};

export type SymbolsPipelinePaths = {
  inputDir: string;
  outputDir: string;
};

// Mirrors the glyphmap house style: m - metadata (p prefix, h input hash),
// s - symbols (icon → symbol name).
export type NanoSymbolMap = {
  m: { p: string; h?: string };
  s: Record<string, string>;
};

export type SymbolsPipelineResult = {
  name: string;
  prefix: string;
  /** Directory containing the generated `.symbolset`/`.imageset` folders. */
  symbolsDir: string;
  /** The generated asset folders (`.symbolset` for symbols, `.imageset` for colored symbols). */
  assetDirs: string[];
  manifestTsPath: string;
  symbolmapPath: string;
  symbols: Record<string, string>;
};

/** "my-tab icons" → "MyTabIconsSymbols" — the manifest export identifier. */
export function manifestExportName(setName: string): string {
  const pascal = setName
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join('');
  const safe = /^[a-zA-Z]/.test(pascal) ? pascal : `Set${pascal}`;
  return `${safe}Symbols`;
}

function manifestTs(
  exportName: string,
  symbols: Record<string, string>
): string {
  const entries = Object.entries(symbols)
    .map(
      ([icon, symbol]) =>
        `  ${JSON.stringify(icon)}: ${JSON.stringify(symbol)},`
    )
    .join('\n');
  return `// Generated by react-native-nano-icons — do not edit.
export const ${exportName} = {
${entries}
} as const;

export type ${exportName.replace(/Symbols$/, '')}SymbolName =
  (typeof ${exportName})[keyof typeof ${exportName}];
`;
}

/**
 * Run the symbol pipeline: prep each SVG, then emit one asset per icon — a
 * monochrome `.symbolset`, or a colored `.imageset` when `multicolor` is set.
 * Also writes a typed manifest and a symbolmap JSON (for build fingerprinting).
 */
export async function runSymbolPipeline(
  config: SymbolsPipelineConfig,
  paths: SymbolsPipelinePaths,
  options?: { logger?: NanoLogger; inputHash?: string }
): Promise<SymbolsPipelineResult> {
  const startTime = Date.now();
  const logger = options?.logger;
  const kind = config.multicolor ? 'colored symbol' : 'symbol';

  logger?.update(`Building ${kind}s "${config.name}"…`);

  ensureDir(paths.outputDir);
  const symbolsDir = path.join(paths.outputDir, `${config.name}.symbols`);
  ensureEmptyDir(symbolsDir);

  const files = (await fsp.readdir(paths.inputDir))
    .filter((f) => f.toLowerCase().endsWith('.svg'))
    .sort();

  const symbols: Record<string, string> = {};
  const assetDirs: string[] = [];

  const PathKit = await PathKitManager.getInstance();

  for (const file of files) {
    const iconName = path.parse(file).name;
    const filePath = path.join(paths.inputDir, file);

    logger?.info(`Processing ${file}`);

    const prepared = await prepareSvgLayers({
      filePath,
      fileLabel: `${config.name}:${file}`,
      PathKit,
      logger,
    });
    if (!prepared) continue;

    const drawable = prepared.paths.filter((p) => !shouldSkipPath(p.d, p.fill));

    if (drawable.length === 0) {
      logger?.warn(`Skipping "${config.name}:${file}": no drawable paths`);
      continue;
    }

    const assetName = `${config.prefix}.${iconName}`;
    let assetDir: string;
    let svgFilename: string;
    let svg: string;
    let contents: string;

    if (config.multicolor) {
      // Colored symbol: original fills/z-order, no knockout.
      assetDir = path.join(symbolsDir, `${assetName}.imageset`);
      svgFilename = `${assetName}.svg`;
      svg = buildColoredSymbolSvg({
        layers: drawable.map((p) => ({ d: p.d, fill: p.fill })),
        viewBox: prepared.viewBox,
        contentBounds:
          contentBounds(
            PathKit,
            drawable.map((p) => p.d)
          ) ?? undefined,
      });
      contents = imagesetContentsJson(svgFilename);
    } else {
      // Monochrome SF Symbol: resolve stacked layers (bake knockouts, occlude)
      // so plates with light details survive monochrome tinting.
      const layers = resolveSymbolLayers(PathKit, drawable, {
        onEraseLayer: () =>
          logger?.info(`    ⊖ Baked white knockout layer into lower layers`),
      });
      assetDir = path.join(symbolsDir, `${assetName}.symbolset`);
      svgFilename = `${assetName}.svg`;
      svg = buildSymbolTemplate({
        layers,
        viewBox: prepared.viewBox,
        contentBounds:
          contentBounds(
            PathKit,
            layers.map((l) => l.d)
          ) ?? undefined,
        descriptiveName: assetName,
        logger,
      });
      contents = symbolsetContentsJson(svgFilename);
    }

    await fsp.mkdir(assetDir, { recursive: true });
    await fsp.writeFile(path.join(assetDir, svgFilename), svg, 'utf8');
    await fsp.writeFile(path.join(assetDir, 'Contents.json'), contents, 'utf8');

    symbols[iconName] = assetName;
    assetDirs.push(assetDir);
  }

  const symbolmapPath = path.join(
    paths.outputDir,
    `${config.name}.symbolmap.json`
  );
  const symbolmap: NanoSymbolMap = {
    m: {
      p: config.prefix,
      ...(options?.inputHash ? { h: options.inputHash } : {}),
    },
    s: symbols,
  };
  await fsp.writeFile(symbolmapPath, JSON.stringify(symbolmap), 'utf8');

  const manifestTsPath = path.join(
    paths.outputDir,
    `${config.name}.symbols.ts`
  );
  await fsp.writeFile(
    manifestTsPath,
    manifestTs(manifestExportName(config.name), symbols),
    'utf8'
  );

  const count = assetDirs.length;
  const elapsed = Date.now() - startTime;
  logger?.succeed(
    `Built ${config.name} ${kind}s [${count} ${kind}${count === 1 ? '' : 's'} in ${elapsed}ms]`
  );

  return {
    name: config.name,
    prefix: config.prefix,
    symbolsDir,
    assetDirs,
    manifestTsPath,
    symbolmapPath,
    symbols,
  };
}
