import fsp from 'node:fs/promises';
import path from 'node:path';

import { PathKitManager } from './managers.js';
import { ensureDir, ensureEmptyDir } from './config.js';
import { prepareSvgLayers } from './prepare.js';
import { shouldSkipPath } from '../svg/svg_dom.js';
import { resolveSymbolLayers, contentBounds } from '../svg/svg_pathops.js';
import { buildSymbolTemplate } from '../symbols/template.js';
import { buildColoredSymbolSvg } from '../symbols/coloredSymbol.js';
import { buildVectorDrawableXml } from '../symbols/vectorDrawable.js';
import {
  symbolsetContentsJson,
  imagesetContentsJson,
} from '../symbols/contents.js';
import {
  toDrawableResourceName,
  manifestBaseName,
} from '../../utils/naming.js';
import type { NanoLogger } from '../types.js';

export type SymbolsPipelineConfig = {
  /** Set name (used for output filenames and the manifest export name). */
  name: string;
  /** Symbol name prefix, e.g. "nano" → "nano.home". */
  prefix: string;
  /** Emit colored `.imageset` (original colors) instead of monochrome `.symbolset`. */
  multicolor?: boolean;
};

export type SymbolsPipelinePaths = {
  inputDir: string;
  outputDir: string;
};

// Mirrors the glyphmap house style: m - metadata (p prefix, h input hash),
// s - symbols (icon → iOS symbol name), d - drawables (icon → Android resource name).
export type NanoSymbolMap = {
  m: { p: string; h?: string };
  s: Record<string, string>;
  d: Record<string, string>;
};

export type SymbolsPipelineResult = {
  name: string;
  prefix: string;
  /** Directory containing the generated `.symbolset`/`.imageset` folders. */
  symbolsDir: string;
  /** The generated asset folders (`.symbolset` for symbols, `.imageset` for colored symbols). */
  assetDirs: string[];
  /** Directory containing the generated Android VectorDrawable `.xml` files. */
  drawablesDir: string;
  /** The generated VectorDrawable `.xml` file paths. */
  drawableFiles: string[];
  /** The generated types-only `.d.ts` (icon-name + iOS-symbol-name unions). */
  dtsPath: string;
  symbolmapPath: string;
  symbols: Record<string, string>;
  /** Icon → Android drawable resource name (e.g. "home" → "nano_home"). */
  drawables: Record<string, string>;
};

function union(values: string[]): string {
  if (values.length === 0) return 'never';
  return values.map((v) => `  | ${JSON.stringify(v)}`).join('\n');
}

/**
 * Types-only manifest (`.d.ts`) — erased by the bundler, so nothing ships in the
 * JS bundle. It augments `NanoSymbolNames` so `nativeNanoSymbol()` accepts this
 * set's filenames with no generic, and exports `${base}Symbol` (iOS asset-catalog
 * names) to feed a `SFSymbolNames` augmentation, plus `${base}Name` (SVG filenames).
 */
function symbolsDts(base: string, symbols: Record<string, string>): string {
  const iconNames = Object.keys(symbols);
  const symbolNames = Object.values(symbols);
  const registry = iconNames
    .map((n) => `    ${JSON.stringify(n)}: true;`)
    .join('\n');
  return `// Generated by react-native-nano-icons — do not edit.
/** Lets nativeNanoSymbol() accept this set's icon names (no generic needed). */
declare module 'react-native-nano-icons/symbols' {
  interface NanoSymbolNames {
${registry}
  }
}

/** SVG filenames in this set. */
export type ${base}Name =
${union(iconNames)};

/** iOS asset-catalog symbol names — augment SFSymbolNames with these. */
export type ${base}Symbol =
${union(symbolNames)};
`;
}

/**
 * Run the symbol pipeline: prep each SVG, then emit one asset per icon — a
 * monochrome `.symbolset`, or a colored `.imageset` when `multicolor` is set.
 * Also writes a typed manifest and a symbolmap JSON (for build fingerprinting).
 */
export async function runSymbolPipeline(
  config: SymbolsPipelineConfig,
  paths: SymbolsPipelinePaths,
  options?: { logger?: NanoLogger; inputHash?: string }
): Promise<SymbolsPipelineResult> {
  const startTime = Date.now();
  const logger = options?.logger;
  const kind = config.multicolor ? 'colored symbol' : 'symbol';

  logger?.update(`Building ${kind}s "${config.name}"…`);

  ensureDir(paths.outputDir);
  const symbolsDir = path.join(paths.outputDir, `${config.name}.symbols`);
  ensureEmptyDir(symbolsDir);
  const drawablesDir = path.join(paths.outputDir, `${config.name}.drawables`);
  ensureEmptyDir(drawablesDir);

  const files = (await fsp.readdir(paths.inputDir))
    .filter((f) => f.toLowerCase().endsWith('.svg'))
    .sort();

  const symbols: Record<string, string> = {};
  const drawables: Record<string, string> = {};
  const assetDirs: string[] = [];
  const drawableFiles: string[] = [];
  const resourceNameToFile = new Map<string, string>();

  const PathKit = await PathKitManager.getInstance();

  for (const file of files) {
    const iconName = path.parse(file).name;
    const filePath = path.join(paths.inputDir, file);

    logger?.info(`Processing ${file}`);

    const prepared = await prepareSvgLayers({
      filePath,
      fileLabel: `${config.name}:${file}`,
      PathKit,
      logger,
    });
    if (!prepared) continue;

    const drawable = prepared.paths.filter((p) => !shouldSkipPath(p.d, p.fill));

    if (drawable.length === 0) {
      logger?.warn(`Skipping "${config.name}:${file}": no drawable paths`);
      continue;
    }

    const assetName = `${config.prefix}.${iconName}`;
    let assetDir: string;
    let svgFilename: string;
    let svg: string;
    let contents: string;
    let vdXml: string;

    if (config.multicolor) {
      // Colored symbol: original fills/z-order, no knockout.
      const coloredLayers = drawable.map((p) => ({ d: p.d, fill: p.fill }));
      const bounds =
        contentBounds(
          PathKit,
          drawable.map((p) => p.d)
        ) ?? undefined;
      assetDir = path.join(symbolsDir, `${assetName}.imageset`);
      svgFilename = `${assetName}.svg`;
      svg = buildColoredSymbolSvg({
        layers: coloredLayers,
        viewBox: prepared.viewBox,
        contentBounds: bounds,
      });
      contents = imagesetContentsJson(svgFilename);
      vdXml = buildVectorDrawableXml({
        layers: coloredLayers,
        multicolor: true,
        viewBox: prepared.viewBox,
        contentBounds: bounds,
      });
    } else {
      // Monochrome SF Symbol: resolve stacked layers (bake knockouts, occlude)
      // so plates with light details survive monochrome tinting.
      const layers = resolveSymbolLayers(PathKit, drawable, {
        onEraseLayer: () =>
          logger?.info(`    ⊖ Baked white knockout layer into lower layers`),
      });
      const bounds =
        contentBounds(
          PathKit,
          layers.map((l) => l.d)
        ) ?? undefined;
      assetDir = path.join(symbolsDir, `${assetName}.symbolset`);
      svgFilename = `${assetName}.svg`;
      svg = buildSymbolTemplate({
        layers,
        viewBox: prepared.viewBox,
        contentBounds: bounds,
        descriptiveName: assetName,
        logger,
      });
      contents = symbolsetContentsJson(svgFilename);
      vdXml = buildVectorDrawableXml({
        layers,
        multicolor: false,
        viewBox: prepared.viewBox,
        contentBounds: bounds,
      });
    }

    await fsp.mkdir(assetDir, { recursive: true });
    await fsp.writeFile(path.join(assetDir, svgFilename), svg, 'utf8');
    await fsp.writeFile(path.join(assetDir, 'Contents.json'), contents, 'utf8');

    // Android resource names are lowercased with every non-[a-z0-9_] run collapsed
    // to "_", so distinct filenames can map to the same name. They must be unique
    // within the set — fail loudly rather than silently renaming, so the runtime
    // helper can derive the name purely from the filename.
    const resourceName = toDrawableResourceName(assetName);
    const clashingFile = resourceNameToFile.get(resourceName);
    if (clashingFile) {
      throw new Error(
        `[react-native-nano-icons] "${config.name}": "${file}" and "${clashingFile}" ` +
          `both map to the Android drawable name "${resourceName}". Rename one of the ` +
          `SVGs so they differ by more than case or non-alphanumeric characters.`
      );
    }
    resourceNameToFile.set(resourceName, file);
    const drawableFile = path.join(drawablesDir, `${resourceName}.xml`);
    await fsp.writeFile(drawableFile, vdXml, 'utf8');

    symbols[iconName] = assetName;
    drawables[iconName] = resourceName;
    assetDirs.push(assetDir);
    drawableFiles.push(drawableFile);
  }

  const symbolmapPath = path.join(
    paths.outputDir,
    `${config.name}.symbolmap.json`
  );
  const symbolmap: NanoSymbolMap = {
    m: {
      p: config.prefix,
      ...(options?.inputHash ? { h: options.inputHash } : {}),
    },
    s: symbols,
    d: drawables,
  };
  await fsp.writeFile(symbolmapPath, JSON.stringify(symbolmap), 'utf8');

  const base = manifestBaseName(config.name);
  const dtsPath = path.join(paths.outputDir, `${config.name}.symbols.d.ts`);
  await fsp.writeFile(dtsPath, symbolsDts(base, symbols), 'utf8');

  const count = assetDirs.length;
  const elapsed = Date.now() - startTime;
  logger?.succeed(
    `Built ${config.name} ${kind}s [${count} ${kind}${count === 1 ? '' : 's'} in ${elapsed}ms]`
  );

  return {
    name: config.name,
    prefix: config.prefix,
    symbolsDir,
    assetDirs,
    drawablesDir,
    drawableFiles,
    dtsPath,
    symbolmapPath,
    symbols,
    drawables,
  };
}
