import fsp from 'node:fs/promises';
import path from 'node:path';

import { ensureDir, ensureEmptyDir, writeFileAtomic } from './config';
import { defaultConcurrency, type SvgWorkerPool } from './iconPool';
import type { SymbolAsset, SymbolTask } from './prepareSymbol';
import {
  prepareIconsWithCache,
  type PreparedSvgCache,
} from './preparedSvgCache';
import {
  toDrawableResourceName,
  toOriginalDrawableResourceName,
  manifestBaseName,
} from '../../utils/naming';
import type { NanoLogger } from '../types';

export type SymbolsPipelineConfig = {
  /** Set name (used for output filenames and the manifest export name). */
  name: string;
  /** Symbol name prefix, e.g. "nano" → "nano.home". */
  prefix: string;
};

export type SymbolsPipelinePaths = {
  inputDir: string;
  outputDir: string;
};

// Mirrors the glyphmap house style: m - metadata (p prefix, h input hash),
// s - symbols (icon → iOS symbol name), d - drawables (icon → Android resource name).
export type NanoSymbolMap = {
  m: { p: string; h?: string };
  s: Record<string, string>;
  d: Record<string, string>;
};

export type SymbolsPipelineResult = {
  name: string;
  prefix: string;
  /** Directory containing the generated `.symbolset` folders. */
  symbolsDir: string;
  /** The generated `.symbolset` folders. */
  assetDirs: string[];
  /** Directory containing the generated Android VectorDrawable `.xml` files. */
  drawablesDir: string;
  /** The generated VectorDrawable `.xml` file paths. */
  drawableFiles: string[];
  /** The generated types-only `.d.ts` (icon-name + iOS-symbol-name unions). */
  dtsPath: string;
  symbolmapPath: string;
  symbols: Record<string, string>;
  /** Icon → Android drawable resource name (e.g. "home" → "nano_home"). */
  drawables: Record<string, string>;
};

function union(values: string[]): string {
  if (values.length === 0) return 'never';
  return values.map((v) => `  | ${JSON.stringify(v)}`).join('\n');
}

/**
 * Types-only manifest (`.d.ts`) — erased by the bundler, so nothing ships in the
 * JS bundle. It augments `NanoSymbolNames` so `nativeNanoSymbol()` accepts this
 * set's filenames with no generic, augments react-navigation's `SFSymbolNames` so
 * the descriptor it returns is accepted as an icon, and exports `${base}Symbol`
 * (iOS asset-catalog names) plus `${base}Name` (SVG filenames).
 *
 * Both augmentations merge across sets, so every set emits its own block.
 */
function symbolsDts(base: string, symbols: Record<string, string>): string {
  const iconNames = Object.keys(symbols);
  const symbolNames = Object.values(symbols);
  return `// Generated by react-native-nano-icons — do not edit.
/** SVG filenames in this set. */
export type ${base}Name =
${union(iconNames)};

/** iOS asset-catalog symbol names. */
export type ${base}Symbol =
${union(symbolNames)};

/** Lets nativeNanoSymbol() accept this set's icon names (no generic needed). */
declare module 'react-native-nano-icons/symbols' {
  interface NanoSymbolNames extends Record<${base}Name, true> {}
}

/** Lets react-navigation accept this set's symbols as a tab-bar/header icon. */
declare module '@react-navigation/native' {
  interface SFSymbolNames extends Record<${base}Symbol, true> {}
}
`;
}

/**
 * Run the symbol pipeline: prep each SVG, then emit one `.symbolset` per icon
 * carrying both the monochrome and the multicolor rendering mode, plus its
 * monochrome and original Android VectorDrawables. Also writes a typed manifest and a symbolmap JSON
 * (for build fingerprinting).
 */
export async function runSymbolPipeline(
  config: SymbolsPipelineConfig,
  paths: SymbolsPipelinePaths,
  options?: {
    logger?: NanoLogger;
    inputHash?: string;
    concurrency?: number;
    preparedSvgCache?: PreparedSvgCache<SymbolTask>;
    svgWorkerPool?: SvgWorkerPool;
    svgHashByFile?: Map<string, string>;
  }
): Promise<SymbolsPipelineResult> {
  const startTime = Date.now();
  const logger = options?.logger;
  const kind = 'symbol';

  logger?.update(`Building ${kind}s "${config.name}"…`);

  const symbolsDir = path.join(paths.outputDir, `${config.name}.symbols`);
  const drawablesDir = path.join(paths.outputDir, `${config.name}.drawables`);

  const files = (await fsp.readdir(paths.inputDir))
    .filter((f) => f.toLowerCase().endsWith('.svg'))
    .sort();

  const failed: string[] = [];

  const results = await prepareIconsWithCache(
    files.map((file) => ({
      kind: 'symbol' as const,
      file,
      filePath: path.join(paths.inputDir, file),
      setName: config.name,
      prefix: config.prefix,
    })),
    options?.concurrency ?? defaultConcurrency(),
    options?.preparedSvgCache,
    options?.svgWorkerPool,
    options?.svgHashByFile
  );

  const resourceNameToFile = new Map<string, string>();
  const assets: {
    iconName: string;
    asset: SymbolAsset;
    resourceName: string;
  }[] = [];

  for (const result of results) {
    for (const [level, msg] of result.logs) logger?.[level](msg);
    if (result.error !== null) {
      logger?.fail(result.error);
      failed.push(result.file);
      continue;
    }
    if (!result.asset) continue;

    // Android resource names are lowercased with every non-[a-z0-9_] run collapsed
    // to "_", so distinct filenames can map to the same name. They must be unique
    // within the set — fail loudly rather than silently renaming, so the runtime
    // helper can derive the name purely from the filename.
    const resourceName = toDrawableResourceName(result.asset.assetName);
    for (const name of [
      resourceName,
      toOriginalDrawableResourceName(resourceName),
    ]) {
      const clashingFile = resourceNameToFile.get(name);
      if (clashingFile) {
        throw new Error(
          `[react-native-nano-icons] "${config.name}": "${result.file}" and "${clashingFile}" ` +
            `both map to the Android drawable name "${name}". Rename one of the ` +
            `SVGs so they differ by more than case or non-alphanumeric characters.`
        );
      }
      resourceNameToFile.set(name, result.file);
    }
    assets.push({
      iconName: result.iconName,
      asset: result.asset,
      resourceName,
    });
  }

  if (failed.length) {
    throw new Error(
      `${failed.length} of ${files.length} icons in [${config.name}] could not be converted: ${failed.join(', ')}`
    );
  }

  ensureDir(paths.outputDir);
  ensureEmptyDir(symbolsDir);
  ensureEmptyDir(drawablesDir);

  const symbols: Record<string, string> = {};
  const drawables: Record<string, string> = {};
  const assetDirs: string[] = [];
  const drawableFiles: string[] = [];

  for (const { iconName, asset, resourceName } of assets) {
    const assetDir = path.join(symbolsDir, asset.assetDirName);
    await fsp.mkdir(assetDir, { recursive: true });
    await fsp.writeFile(
      path.join(assetDir, asset.svgFilename),
      asset.svg,
      'utf8'
    );
    await fsp.writeFile(
      path.join(assetDir, 'Contents.json'),
      asset.contents,
      'utf8'
    );
    const drawableFile = path.join(drawablesDir, `${resourceName}.xml`);
    await fsp.writeFile(drawableFile, asset.vdXml, 'utf8');
    const originalDrawableFile = path.join(
      drawablesDir,
      `${toOriginalDrawableResourceName(resourceName)}.xml`
    );
    await fsp.writeFile(originalDrawableFile, asset.vdOriginalXml, 'utf8');

    symbols[iconName] = asset.assetName;
    drawables[iconName] = resourceName;
    assetDirs.push(assetDir);
    drawableFiles.push(drawableFile, originalDrawableFile);
  }

  const symbolmapPath = path.join(
    paths.outputDir,
    `${config.name}.symbolmap.json`
  );
  const symbolmap: NanoSymbolMap = {
    m: {
      p: config.prefix,
      ...(options?.inputHash ? { h: options.inputHash } : {}),
    },
    s: symbols,
    d: drawables,
  };
  writeFileAtomic(symbolmapPath, JSON.stringify(symbolmap));

  const base = manifestBaseName(config.name);
  const dtsPath = path.join(paths.outputDir, `${config.name}.symbols.d.ts`);
  writeFileAtomic(dtsPath, symbolsDts(base, symbols));

  const count = assetDirs.length;
  const elapsed = Date.now() - startTime;
  logger?.succeed(
    `Built ${config.name} ${kind}s [${count} ${kind}${count === 1 ? '' : 's'} in ${elapsed}ms]`
  );

  return {
    name: config.name,
    prefix: config.prefix,
    symbolsDir,
    assetDirs,
    drawablesDir,
    drawableFiles,
    dtsPath,
    symbolmapPath,
    symbols,
    drawables,
  };
}
